# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: songchaow
email: songchaow@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  a light-weight blog newly created
# baseurl: "/~wscwdy" # the subpath of your site, e.g. /blog
url: "https://www.songchaow.cn" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name             : "songchaow"
  avatar           : "/assets/images/kaguya-square.jpg"
  bio              : "A candidate for software engineer, passionate for computer graphics(especially in rendering), and fond of music theory."
  location         : "Hefei, Anhui, China"
  email            : "songchaow@outlook.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/songchaow"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
      hidden: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "custom"
  
# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"
paginate: 5
paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
#  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
#  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
